### PR TITLE
Package strip

### PR DESCRIPTION
**Pull request by saxtot**
Stripped down the packages to only what we need to save on build time.
The initial closing bug is not in the scope of this PR, sadly. 
This has been tested on Markhor multiple times.

### CODE REVIEW

**Comment by benmalenfant** [comment]
Need to bring back the gripper urdf, this causes issues with markhor_description

**Comment by saxtot** [comment]
> Need to bring back the gripper urdf, this causes issues with markhor_description
> 

Wasn't that what you did in your last commit on this very branch?

**Comment by benmalenfant** [comment]
Oops my bad, assumed i forgot to do it, should be good then😄

**Comment by GLDuval** [comment]
Looks good, the deleted code looks unnecessary for us.

**Review by GLDuval — APPROVED** [review]

**Review by Leo-Dan — APPROVED** [review]

**Comment by Leo-Dan** [comment]
Very cool ! No more garbage.

**Pull request merged**
